### ISSUE TITLE
Installation de Java sur la sandbox 

### ISSUE THREAD

**Issue by nimdanor** [plgitlogin/sandbox#19]
Java is installed on the sandbox at this date 7/2/2019 .
but there is a need for a junit tester that was proposed by R. Forax. 
github.com/forax/first-language

**Comment by nimdanor** [comment]
l'idée est d'installer aussi ces logiciels (la version, 1.0.2 devrai créer les exécutables pl-java,  pl-javac
qu'il faut mettre dans le PATH.

**Comment by qcoumes** [comment]
Il y a déjà un tester junit, mon grader Java s'en sert.

**Comment by qcoumes** [comment]
Je regarderais pour installer ses versions quand j'aurais accès à un ordinateur.

**Comment by qcoumes** [comment]
Solved on 1.0.0
